"""empty message

Revision ID: f5bead773dc4
Revises: None
Create Date: 2017-06-13 23:02:02.454011

"""

# revision identifiers, used by Alembic.
revision = 'f5bead773dc4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coursename', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentname', sa.String(length=250), nullable=False),
    sa.Column('degree', sa.String(length=250), nullable=False),
    sa.Column('major', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('courses')
    # ### end Alembic commands ###
